### PR TITLE
forgor to remove useless stuff + add new translation + convar thing

### PR DESCRIPTION
**Pull request by TonybynMp4**
Adds the translation to the latest changes, removes useless things i tested and forgot to remove and restructures the locales

### CODE REVIEW

**Comment by Andyauk** [comment]
I seem to get the error

```
[script:qb-luckywheel] Warning: Missing phrase for key: "general.Marked"
[script:qb-luckywheel] Warning: Missing phrase for key: "success.You_Won"
```

and

`warning missing phrase for key: "spin_wheel"`

**Comment by TonybynMp4** [comment]
should be fixed :p

**Comment by Andyauk** [comment]
> should be fixed :p

still the same. I see in locales en it would be `You_Won` not `You_won`
put back to `Spin_Wheel` in locales en also

the final error `warning missing phrase for key: "spin_wheel"` only shows up if your not using the 3rd eye option.

**Comment by TonybynMp4** [comment]
ok this time it should be good

**Comment by Andyauk** [comment]
> ok this time it should be good

I'll check later 😊

**Comment by Andyauk** [comment]
<a href="https://ibb.co/BNSyXy8">error</a>

I don't understand it. as I've looked though the code.

**Comment by TonybynMp4** [comment]
ok try now lol

**Comment by Andyauk** [comment]
> ok try now lol

no I really don't get it,

**Comment by TonybynMp4** [comment]
should work tho tf

**Comment by Andyauk** [comment]
> should work tho tf

yes it should. I've looked over and over and changed stuff myself. to see. i don't get it. if you turn on target, you get a f8 message when you get into city, if you have target tuned off, your f8 gets spammed with it.

**Comment by TonybynMp4** [comment]
ok i fucking get it now

**Comment by TonybynMp4** [comment]
now it should work

**Comment by Andyauk** [comment]
> now it should work

ill check on restart later, as in RP. but good notice, I think that might be it. lol

**Comment by Andyauk** [comment]
> now it should work

no errors, but this needs fixing

<a href="https://imgbb.com/">casinowheel</a><br /><a target='_blank' href='https://imgbb.com/'>add image to html</a><br />

**Comment by TonybynMp4** [comment]
Should be good now 😮‍💨

**Comment by Andyauk** [comment]
> Should be good now 😮‍💨

All good buddy
.
Only issue now, is it lands on the wrong image to what you get, and at times Inventory full message when I'm not.

**Comment by TonybynMp4** [comment]
That i won't be able to fix tho 😂

**Comment by Andyauk** [comment]
> That i won't be able to fix tho 😂

true. but everything is working. so all good.

**Comment by TonybynMp4** [comment]
added the convar thing qb uses now 👍🏻

**Comment by TonybynMp4** [comment]
@ItsANoBrainer my brother in Christ merge this already 🤨

**Comment by ItsANoBrainer** [comment]
yolo

**Comment by TonybynMp4** [comment]
no fucking way it happened

**Pull request merged**
